name: 정기 릴리즈를 위한 ChangeLog 생성

on:
  workflow_dispatch:
    inputs:
      sprint_number:
        description: '스프린트 번호'
        required: true
        default: '90'
  # schedule:
  #   - cron: "0 9 * * 1"  # 예: 매주 월요일 오전 9시에 실행 (UTC 기준)
  # push:
  #   branches:
  #     - 'release/*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # 브랜치 최신화
      - name: Update remote branches
        run: git remote update

      - name: Checkout and update develop branch
        run: |
          git checkout develop
          git pull origin develop

      - name: Checkout and update master branch
        run: |
          git checkout master
          git pull origin master

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.0'

      # 릴리즈 브랜치 생성
      - name: Install git flow
        run: |
          sudo apt-get update
          sudo apt-get install -y git-flow

      - name: Get today's date
        id: get_date
        run: |
          echo "today_date=$(node -e 'const today = new Date(); console.log(`${today.getFullYear()}${String(today.getMonth() + 1).padStart(2, "0")}${String(today.getDate()).padStart(2, "0")}`)')" >> $GITHUB_ENV

      - name: Start Release with git flow
        run: |
          echo "Today date is: ${{ env.today_date }}"
          git flow init -d
          echo "Done: git flow init"
          git flow release start -F ${{ env.today_date }}
          echo "Done: git flow release start"
          git flow release publish ${{ env.today_date }}
          echo "Done: git flow release publish"
          yarn run version
          echo "Done: yarn version"

      - name: Commit and push CHANGELOG.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md"
          git push origin release/${{ github.ref_name }}

      - name: Send Slack Message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.TEST_CHANNEL_ID }}
          payload: |
            {
              "text": "release message",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{github.event.inputs.sprint_number}} 스프린트 릴리즈 열차가 출발합니다 🚂",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "브랜치: <https://github.com/ellen-lee-goorm/gds-onboarding/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "rich_text",
                  "elements": [
                    {
                      "type": "rich_text_section",
                      "elements": [
                        {
                          "type": "text",
                          "text": "${{github.event.inputs.sprint_number}} 스프린트에는 ...",
                          "style": {
                            "bold": true
                          }
                        },
                        {
                          "type": "text",
                          "text": "\n\n"
                        }
                      ]
                    },
                    {
                      "type": "rich_text_list",
                      "style": "bullet",
                      "indent": 0,
                      "border": 0,
                      "elements": [
                        {
                          "type": "rich_text_section",
                          "elements": [
                            {
                              "type": "text",
                              "text": "업데이트1"
                            }
                          ]
                        },
                        {
                          "type": "rich_text_section",
                          "elements": [
                            {
                              "type": "text",
                              "text": "업데이트1"
                            }
                          ]
                        },
                        {
                          "type": "rich_text_section",
                          "elements": [
                            {
                              "type": "text",
                              "text": "업데이트1"
                            }
                          ]
                        },
                        {
                          "type": "rich_text_section",
                          "elements": [
                            {
                              "type": "text",
                              "text": "업데이트1"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "승인"
                      },
                      "style": "primary",
                      "value": "accept release"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "거절"
                      },
                      "style": "danger",
                      "value": "reject release"
                    }
                  ]
                }
              ]
            }

        env:
          SLACK_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
